---
title: "Process Capability ShearedSheet"
output: html_document
date: "2024-09-22"
---


```{r}
# Startup Code
require(lolcat)
require(formattable)
ro<-round.object
nqtr<-function(x,d){noquote(t(round.object(x, d)))}
options(scipen=999)
```

```{r}
# *** Load Data ***
sheet <- read.csv("ShearedSheet.dat", sep="")
View(sheet)

```

```{r}
# Descriptive Statistics and Histogram ------------------------------------
nqtr(summary.continuous(sheet$Width_Deviation), 5)
```


```{r}
summary(sheet$Width_Deviation)
```

```{r}

# Descriptive Statistics and Histogram ------------------------------------
hist.grouped(sheet$Width_Deviation, stat.lsl = NA, stat.usl = 7, stat.target = 0, main = "Histogram of Sheets",freq = F)

hist.add.distribution.curve.normal(sheet$Width_Deviation
                                   ,lwd=2
                                   ,freq=F)


```
```{r}
# Test for normality within subgroups -------------------------------------
subgroup_norm<-ro(summary.continuous(fx = Width_Deviation~Subgroup, data = sheet, stat.mean = F, stat.var = F, stat.miss = F),4)
require(formattable)
formattable(subgroup_norm)
View(subgroup_norm)
```


```{r}
# Create the Control Chart ------------------------------------------------
spcxbar.s<-spc.chart.variables.mean.and.meanstandarddeviation(data = sheet$Width_Deviation
                                                              ,sample = sheet$Subgroup
                                                              ,stat.lsl = NA
                                                              ,stat.target = 0
                                                              ,stat.usl = 7
                                                              ,chart1.main = "Mean Chart of Sheets"
                                                              ,chart2.main = "Standard Deviation Chart")
```

```{r}
# Calculate estimate of sigma from control chart --------------------------
(sbar<-mean(spcxbar.s$parameter.standard.deviations))
(c4<-spc.constant.calculation.c4(8))
(sig_est.s<-sbar/c4)
```

```{r}
# Calculate the Natural Tolerance
nt_est <- 6*sig_est.s
nt_est
```

```{r}
### Draw Exp Curve and Histogram - Correct


hist.grouped(sheet$Width_Deviation
             ,xlim=c(min(sheet$Width_Deviation)-1,max(sheet$Width_Deviation))
             ,ylim=c(0,1)
             ,anchor.value = min(sheet$Width_Deviation)
             ,stat.target = 0
             ,stat.usl = 7
             ,main = "Sheet"
             ,freq=F)
hist.add.distribution.curve.exp.low(x = sheet$Width_Deviation
                                    ,low = min(sheet$Width_Deviation)
                                    ,lwd=2
                                    ,freq = F)
```


```{r}
# Exponential Test ------------------------------------------------
shapiro.wilk.exponentiality.test(x = sheet$Width_Deviation)
```

```{r}
# Alternative Approach: Kolmogorov-Smirnov Test
ks.test(sheet$Width_Deviation, "pexp", rate=1/mean(sheet$Width_Deviation))

```

```{r}
# Alternative Approach: Anderson-Darling Test

library(nortest)
ad.test(sheet$Width_Deviation)

```

```{r}
require(ADGofTest)
#ad.test(sheet$Width_Deviation, null="pexp", rate=1/mean(sheet$Width_Deviation))

```

```{r}
# Generate 3 sigma chart limits for the X chart ------------------------------------
(nt.exp.low<-ro(natural.tolerance.exp.low(x = sheet$Width_Deviation
                                          ,low = min(sheet$Width_Deviation)),5))
```

```{r}
# Find the UNPL and LNPL --------------------------
(LNPL.exp.low<-nt.exp.low$lower.limit)
(UNPL.exp.low<-nt.exp.low$upper.limit)
```



```{r}
#  **** Capability and Performance Indices **** ---------------------------
(cap.xbar.s<-ro(spcxbar.s$capability,4))
formattable(cap.xbar.s)
```

```{r}
# Cp only
spcxbar.s$capability[1,1:4]

# Cpk only
spcxbar.s$capability[2,1:4]
```

```{r}
USL<-7
xbar<-mean(sheet$Width_Deviation)
```



```{r}
spc.capability.cpU.simple(upper.specification = USL
                          ,process.center = xbar
                          ,process.variability = sig_est.s^2
                          ,n.sigma = 6)
```

```{r}
spc.capability.cpL.simple(lower.specification = NA
                          ,process.center = xbar
                          ,process.variability = sig_est.s^2
                          ,n.sigma = 6)
```








```{r}
# Capability Assessment -------------------------------------
# Now we can evaluate capability
data<-sheet$Width_Deviation
data
```

```{r}
# Define function for natural tolerance -----------------------------------
# Get natural tolerance for Exponential Low Distribution for the individual values
nt.exp.low<-natural.tolerance.exp.low(x = sheet$Width_Deviation,low = min(sheet$Width_Deviation))

nt.exp.low

ro(formattable(nt.exp.low),4)

```

```{r}
# Define inputs -----------------------------------------------------------
LSL       <- NA
Target    <- 0
USL       <- 7
l.out     <- pexp.low(q = LSL, low = min(data), mean = mean(data), lower.tail = T)
u.out     <- pexp.low(q = USL, low = min(data), mean = mean(data), lower.tail = F)
total.out <- u.out
median    <- median(data)
mean      <- mean(data)
nt_est    <- nt.exp.low$natural.tolerance
s         <- sd(data)
obs.above.spec <- sum(data > USL)
obs.below.spec <- sum(data < LSL)
totaln         <- length(data)

```

```{r}
# Capability and Performance Indices --------------------------------------
cap.exp<-spc.capability.summary.ungrouped.nonnormal.simple.R(stat.lsl = LSL
                                                    ,stat.target = Target
                                                    ,stat.usl = USL
                                                    ,process.center.capability = median
                                                    ,process.center.performance = mean
                                                    ,process.variability = s^2
                                                    ,process.n.upper = obs.above.spec
                                                    
                                                    ,process.n       = totaln
                                                    ,natural.tolerance = nt_est
                                                    
                                                    ,p.upper           = u.out)

ro(cap.exp,4)

ro(formattable(cap.exp),4)
```

```{r}
# Cp Only ----------------------------------------------
# Sample data
data <- data

# Define specification limits
lower_SL <- NA
upper_SL <- 7

# Calculate the median
X_median <- median(data)

# Calculate natural tolerance (for example, using the range)
NT <- 8.17689

# Calculate Cp
Cp <- (2 * abs(X_median - upper_SL)) / NT

Cp

```


```{r}
spc.capability.cp.simple(lower.specification = NA, upper.specification = 7, 
                         process.center = median(data), process.natural.tolerance = 8.1769)
```

```{r}
spc.capability.cpk.simple(lower.specification = NA, upper.specification = 7, 
                          process.variability = s^2, process.center = median(data))
```



