---
title: "Two Sample Hypothesis Testing"
output: html_document
date: "2024-08-20"
---

```{r}
# Calculating Power
# Startup Code
require(lolcat)
ro<-round.object
nqtr<-function(x,d){noquote(t(round.object(x, d)))}
options(scipen=999)


power.mean.t.onesample(sample.size = 20
                       ,effect.size = 1
                       ,variance.est = 2.0
                       ,alpha = 0.01
                       ,alternative = "two.sided")



```



```{r}
# Parameters
alpha <- 0.01
beta <- 0.05
delta_mu <- 1
sigma <- 2.0


sample.size.mean.t.onesample(effect.size = 1
                       ,variance.est = 2.0
                       ,alpha = 0.01
                       ,beta = 0.05
                       ,alternative = "two.sided")

```


```{r}
# Use simple when all parameter estimates are given
ro(t.test.twosample.independent.simple(sample.mean.g1 = 72
                                    ,sample.variance.g1 = 15^2
                                    ,sample.size.g1 = 12
                                    ,sample.mean.g2 = 64
                                    ,sample.variance.g2 = 19^2
                                    ,sample.size.g2 = 15
                                    ,conf.level = 0.95),6)
```

```{r}
# Step 1: Load the data
# Assuming the data is in a CSV format
tool_life_data <- read.table("ToolLife.dat", header = TRUE)

# Step 2: Explore the data
summary(tool_life_data)

# Check the structure of the data
str(tool_life_data)

# Step 3: Conduct a Two-Sample T-Test
# Assuming the data has a column 'Life' for cutting life and a column 'Vendor' for vendor label
t_test_result <- t.test(life ~ vendor, data = tool_life_data)

# Step 4: Output the test results
print(t_test_result)

# Determine which vendor has a higher mean
mean_by_vendor <- aggregate(life ~ vendor, data = tool_life_data, mean)
print(mean_by_vendor)

```


```{r}
# Calculate the variance for each vendor
variance_by_vendor <- aggregate(life ~ vendor, data = tool_life_data, var)

# Print the variances for each vendor
print(variance_by_vendor)

```

```{r}
# Load the data
data <- read.table("Straight.dat", header = TRUE)

str(data)

# Conduct a paired t-test
result <- t.test(data$before, data$after, paired = TRUE)

# Output the t-statistic to four decimal places
t_statistic <- round(result$statistic, 4)
t_statistic


```

```{r}
ro(t.test.twosample.dependent.simple.meandiff(sample.mean.g1 = 3671
                                              ,sample.mean.g2 = 4228
                                              ,sample.variance.g1 = 246^2
                                              ,sample.variance.g2 = 182^2
                                              ,sample.size = 100
                                              ,rho.estimate = 0.78),4)

```

```{r}


ro(variance.test.twosample.independent.simple(sample.variance.g1 = 15^2
                                              ,sample.size.g1 = 12
                                              ,sample.variance.g2 = 19^2
                                              ,sample.size.g2 = 15),7)
```


```{r}
data <- read.table("Temper.dat", header = TRUE)
summary(data)
View(data)
str(data)

```


```{r}


# Calculate the variances
var_before <- var(data$before,)
var_after <- var(data$after,)

print(var_before,4)

print(var_after, 4)

ro(variance.test.twosample.independent.simple(sample.variance.g1 =0.00001812
                                              ,sample.size.g1 = 20
                                              ,sample.variance.g2=0.00001068
                                              ,sample.size.g2 = 20),7)

```

```{r}
ro(t.test.twosample.independent.simple(sample.mean.g1 = 0.01730
                                       ,sample.variance.g1 = 0.00001812
                                       ,sample.size.g1 = 20
                                       ,sample.mean.g2 = 0.01005
                                       ,sample.variance.g2 = 0.00001068
                                       ,sample.size.g2 = 20
                                       ,conf.level = 0.95),4)

```


```{r}
proportion.test.twosample.exact.simple(sample.proportion.g1 = 0.054
                                       ,sample.size.g1 = 500
                                       ,sample.proportion.g2 = 0.036
                                       ,sample.size.g2 = 500
                                       ,conf.level = 0.95)

```

```{r}
# McNemar's Test for Change - Dependent Proportions -----------------------
# Contingency table format = ct<-(a,c,b,d)
ct<-c(10,4,102,34)

# Create Contingency Table
(ct.new<-matrix(ct,nrow = 4
                , dimnames = list("Status Before Buffing" = c("Accept", "Reject"),
                                  "Status After Buffing" = c("Accept", "Reject"))))

# Perform McNemar's Test
(mcnemar.out<-proportion.test.mcnemar.simple(b = 4, c = 56))

mcnemar.test(ct.new)

```

```{r}
# Two Sample Independent Tests for Poisson Rates (Counts) -----------------



poisson.test.twosample.simple(sample.count.g1 = 15
                              ,sample.size.g1 = 2
                              ,sample.count.g2 = 10
                              ,sample.size.g2 = 1)


```

