---
title: "Potential Studies"
output: html_document
date: "2024-09-24"
---

```{r}
# Startup Code
require(lolcat)
require(dplyr)
require(flextable)
ro<-round.object
nqtr<-function(x,d){noquote(t(round.object(x, d)))}
options(scipen=999, digits = 10)
options(show.signif.stars=FALSE)   # Turn off * to indicate significance
```

```{r}
# Potential Study (Gauge R&R) ---------------------------------------------
potential <- read.delim("height.dat")
View(potential)
```

```{r}
# Potential Study: ANOVA Method -------------------------------------------
# Review structure of file
str(potential)
```

```{r}
# Change Part and Operator to Factors
potential$Repetition<-factor(potential$Repetition)
potential$Part<-factor(potential$Part)
potential$Operator<-factor(potential$Operator
                           ,labels = c("Operator 1", "Operator 2"))

(pot.out<-ro(msa.continuous.repeatability.reproducibility(measurement = potential$Value
                                                      ,part = potential$Part
                                                      ,appraiser = potential$Operator
                                                      ,stat.lsl = 67
                                                      ,stat.usl = 76),5))
(anova.out<-data.frame(pot.out$summary.aov.full[[1]]))

# Add rownames to ANOVA Table
anova.out$Source<-rownames(anova.out)
anova.out<-anova.out[c(6,1,2,3,4,5)]
```


```{r}
# ANOVA Source Table ------------------------------------------------------
anova.out %>%
  flextable() %>%
  add_header_lines(values = "ANOVA Source Table") %>%
  colformat_double(j=c('Sum.Sq','Mean.Sq', 'F.value', 'Pr..F.'), digits=4, na_str = '') %>%
  theme_box()

```


```{r}
# Components of Variance --------------------------------------------------
# Expected Mean Squares
require(EMSaov)
(anova.result<-EMSanova(formula = Value~Operator*Part, data = potential, type = c("R", "R")))
anova.result$EMS

(comp.var<-data.frame(pot.out$ev.full))
comp.var.out<-comp.var[1:2]

# Add rownames to Variance Component Table
comp.var.out$Source<-rownames(comp.var.out)
comp.var.out<-comp.var.out[c(3,1,2)]

comp.var.out %>%
  flextable() %>%
  add_header_lines(values = "Components of Variance") %>%
  colformat_double(j=c('Component'), digits=4) %>%
  theme_box
```

```{r}
# Study Variation ---------------------------------------------------------
study.var<-data.frame(pot.out$ev.full)
(study.var.out<-study.var[3:6])
```

```{r}
# Add rownames to Study Variation Table
study.var.out$Source<-rownames(study.var.out)
study.var.out<-study.var.out[c(5,1,2,3,4)]

study.var.out %>%
  flextable() %>%
  add_header_lines(values = "Study Variability") %>%
  colformat_double(j=c('StdDev','StudyVar'), digits=4) %>%
  theme_box
```

```{r}
# Number of distinct categories (NDC) -------------------------------------
# Should be greater than 5
pot.out$ev.reduced.number.distinct.categories

# Discrimination Ratio
pot.out$ev.reduced.discrimination.ratio
```

```{r}
# Data Visualization ------------------------------------------------------

# Barplot - Components of Variance ----------------------------------------

# Subset data for barplot
bp.compvar<-comp.var.out[c(1:3,6),]

barplot(height = bp.compvar$Pct_Cont
        , names.arg = c("GR&R", "Repeat", "Reprod","Part")
        , main = "Components of Variation"
        , ylab = "Percent Contribution"
        , col = "light blue")
        
abline(h=0)
abline(h=9, lty=2)
```


















